/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAIHOCTUAN4;
import java.sql.*;


import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author admin
 */
public class baitaptuan4 extends javax.swing.JFrame {

    /**
     * Creates new form baitaptuan4
     */
    public baitaptuan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPgoc = new javax.swing.JPanel();
        jPtieude = new javax.swing.JPanel();
        jTtieude = new javax.swing.JTextField();
        jPnoidungchinh = new javax.swing.JPanel();
        jPmenu = new javax.swing.JPanel();
        jBRong = new javax.swing.JButton();
        jBSID_menu = new javax.swing.JButton();
        jBSName_menu = new javax.swing.JButton();
        jBBooks_menu = new javax.swing.JButton();
        jBNews = new javax.swing.JButton();
        jBJournals = new javax.swing.JButton();
        jPchinhsua = new javax.swing.JPanel();
        jBNew = new javax.swing.JButton();
        jBSave = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBUpdate = new javax.swing.JButton();
        jPnoidung = new javax.swing.JPanel();
        jLSID = new javax.swing.JLabel();
        jLSName = new javax.swing.JLabel();
        jLType = new javax.swing.JLabel();
        jLAddress = new javax.swing.JLabel();
        jLMail = new javax.swing.JLabel();
        jLContact = new javax.swing.JLabel();
        jLRemarks = new javax.swing.JLabel();
        jTSID = new javax.swing.JTextField();
        jTAddress = new javax.swing.JTextField();
        jCBooks = new javax.swing.JCheckBox();
        jCNews = new javax.swing.JCheckBox();
        jCJournals = new javax.swing.JCheckBox();
        jTEmail = new javax.swing.JTextField();
        jTSName = new javax.swing.JTextField();
        jTContact = new javax.swing.JTextField();
        jSCP = new javax.swing.JScrollPane();
        jTRemarks = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPgoc.setLayout(new java.awt.BorderLayout());

        jPtieude.setForeground(new java.awt.Color(0, 102, 102));

        jTtieude.setBackground(new java.awt.Color(0, 102, 102));
        jTtieude.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTtieude.setForeground(new java.awt.Color(255, 255, 255));
        jTtieude.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTtieude.setText("Books Suppliers");

        javax.swing.GroupLayout jPtieudeLayout = new javax.swing.GroupLayout(jPtieude);
        jPtieude.setLayout(jPtieudeLayout);
        jPtieudeLayout.setHorizontalGroup(
            jPtieudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTtieude, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        jPtieudeLayout.setVerticalGroup(
            jPtieudeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPtieudeLayout.createSequentialGroup()
                .addComponent(jTtieude, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPgoc.add(jPtieude, java.awt.BorderLayout.PAGE_START);

        jPnoidungchinh.setBackground(new java.awt.Color(255, 255, 255));

        jPmenu.setBackground(new java.awt.Color(255, 255, 255));

        jBRong.setBackground(new java.awt.Color(102, 0, 204));
        jBRong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBRong.setForeground(new java.awt.Color(255, 255, 255));
        jBRong.setBorder(null);

        jBSID_menu.setBackground(new java.awt.Color(102, 0, 204));
        jBSID_menu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBSID_menu.setForeground(new java.awt.Color(255, 255, 255));
        jBSID_menu.setText("Supplier ID");
        jBSID_menu.setBorder(null);
        jBSID_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSID_menuActionPerformed(evt);
            }
        });

        jBSName_menu.setBackground(new java.awt.Color(102, 0, 204));
        jBSName_menu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBSName_menu.setForeground(new java.awt.Color(255, 255, 255));
        jBSName_menu.setText("Supplier Name");
        jBSName_menu.setBorder(null);

        jBBooks_menu.setBackground(new java.awt.Color(102, 0, 204));
        jBBooks_menu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBBooks_menu.setForeground(new java.awt.Color(255, 255, 255));
        jBBooks_menu.setText("Books");
        jBBooks_menu.setBorder(null);

        jBNews.setBackground(new java.awt.Color(102, 0, 204));
        jBNews.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBNews.setForeground(new java.awt.Color(255, 255, 255));
        jBNews.setText("News Paper");
        jBNews.setBorder(null);

        jBJournals.setBackground(new java.awt.Color(102, 0, 204));
        jBJournals.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBJournals.setForeground(new java.awt.Color(255, 255, 255));
        jBJournals.setText("Journals and Magazines");
        jBJournals.setBorder(null);

        javax.swing.GroupLayout jPmenuLayout = new javax.swing.GroupLayout(jPmenu);
        jPmenu.setLayout(jPmenuLayout);
        jPmenuLayout.setHorizontalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmenuLayout.createSequentialGroup()
                .addComponent(jBRong, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBSID_menu)
                .addGap(0, 0, 0)
                .addComponent(jBSName_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBBooks_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBNews, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBJournals, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPmenuLayout.setVerticalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmenuLayout.createSequentialGroup()
                .addGroup(jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBRong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSID_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jBSName_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBooks_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBNews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBJournals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPchinhsua.setBackground(new java.awt.Color(255, 255, 255));
        jPchinhsua.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.gray, null));

        jBNew.setBackground(new java.awt.Color(0, 102, 102));
        jBNew.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBNew.setForeground(new java.awt.Color(255, 255, 255));
        jBNew.setText("New");
        jBNew.setBorder(null);

        jBSave.setBackground(new java.awt.Color(255, 102, 0));
        jBSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBSave.setForeground(new java.awt.Color(255, 255, 255));
        jBSave.setText("Save");
        jBSave.setBorder(null);
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jBDelete.setBackground(new java.awt.Color(0, 102, 102));
        jBDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBDelete.setForeground(new java.awt.Color(255, 255, 255));
        jBDelete.setText("Delete");
        jBDelete.setBorder(null);

        jBUpdate.setBackground(new java.awt.Color(153, 0, 51));
        jBUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jBUpdate.setText("Update");
        jBUpdate.setBorder(null);

        javax.swing.GroupLayout jPchinhsuaLayout = new javax.swing.GroupLayout(jPchinhsua);
        jPchinhsua.setLayout(jPchinhsuaLayout);
        jPchinhsuaLayout.setHorizontalGroup(
            jPchinhsuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPchinhsuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNew, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPchinhsuaLayout.setVerticalGroup(
            jPchinhsuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPchinhsuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPchinhsuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPnoidung.setBackground(new java.awt.Color(255, 255, 255));
        jPnoidung.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), java.awt.Color.white));

        jLSID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLSID.setText("Supplier ID");
        jLSID.setMaximumSize(new java.awt.Dimension(52, 15));
        jLSID.setMinimumSize(new java.awt.Dimension(52, 15));
        jLSID.setPreferredSize(new java.awt.Dimension(52, 15));

        jLSName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLSName.setText("Supplier Name");
        jLSName.setMaximumSize(new java.awt.Dimension(52, 15));
        jLSName.setMinimumSize(new java.awt.Dimension(52, 15));
        jLSName.setPreferredSize(new java.awt.Dimension(52, 15));

        jLType.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLType.setText("Supplier Type");
        jLType.setMaximumSize(new java.awt.Dimension(52, 15));
        jLType.setMinimumSize(new java.awt.Dimension(52, 15));
        jLType.setPreferredSize(new java.awt.Dimension(52, 15));

        jLAddress.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLAddress.setText("Address");
        jLAddress.setMaximumSize(new java.awt.Dimension(52, 15));
        jLAddress.setMinimumSize(new java.awt.Dimension(52, 15));
        jLAddress.setPreferredSize(new java.awt.Dimension(52, 15));

        jLMail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLMail.setText("Email ID");
        jLMail.setMaximumSize(new java.awt.Dimension(52, 15));
        jLMail.setMinimumSize(new java.awt.Dimension(52, 15));
        jLMail.setPreferredSize(new java.awt.Dimension(52, 15));

        jLContact.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLContact.setText("Contact No");
        jLContact.setMaximumSize(new java.awt.Dimension(52, 15));
        jLContact.setMinimumSize(new java.awt.Dimension(52, 15));
        jLContact.setPreferredSize(new java.awt.Dimension(52, 15));

        jLRemarks.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLRemarks.setText("Remarks");
        jLRemarks.setMaximumSize(new java.awt.Dimension(52, 15));
        jLRemarks.setMinimumSize(new java.awt.Dimension(52, 15));
        jLRemarks.setPreferredSize(new java.awt.Dimension(52, 15));

        jCBooks.setBackground(new java.awt.Color(255, 255, 255));
        jCBooks.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCBooks.setText("Books");

        jCNews.setBackground(new java.awt.Color(255, 255, 255));
        jCNews.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCNews.setText("News Papers");

        jCJournals.setBackground(new java.awt.Color(255, 255, 255));
        jCJournals.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCJournals.setText("Journals and Magazines");

        jTRemarks.setColumns(20);
        jTRemarks.setRows(5);
        jSCP.setViewportView(jTRemarks);

        javax.swing.GroupLayout jPnoidungLayout = new javax.swing.GroupLayout(jPnoidung);
        jPnoidung.setLayout(jPnoidungLayout);
        jPnoidungLayout.setHorizontalGroup(
            jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnoidungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnoidungLayout.createSequentialGroup()
                        .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnoidungLayout.createSequentialGroup()
                                .addComponent(jLSID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTSID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnoidungLayout.createSequentialGroup()
                                .addComponent(jLSName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTSName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnoidungLayout.createSequentialGroup()
                                .addComponent(jLMail, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnoidungLayout.createSequentialGroup()
                                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLType, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLContact, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPnoidungLayout.createSequentialGroup()
                                        .addComponent(jCBooks)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCNews)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCJournals))
                                    .addComponent(jTContact, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(98, Short.MAX_VALUE))
                    .addGroup(jPnoidungLayout.createSequentialGroup()
                        .addComponent(jLRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSCP)
                        .addGap(109, 109, 109))))
        );
        jPnoidungLayout.setVerticalGroup(
            jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnoidungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLSID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTSID, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTSName))
                .addGap(12, 12, 12)
                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBooks)
                    .addComponent(jCNews)
                    .addComponent(jCJournals))
                .addGap(12, 12, 12)
                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContact, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jTContact))
                .addGap(12, 12, 12)
                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEmail))
                .addGroup(jPnoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnoidungLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnoidungLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPnoidungchinhLayout = new javax.swing.GroupLayout(jPnoidungchinh);
        jPnoidungchinh.setLayout(jPnoidungchinhLayout);
        jPnoidungchinhLayout.setHorizontalGroup(
            jPnoidungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPnoidungchinhLayout.createSequentialGroup()
                .addGroup(jPnoidungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPchinhsua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPnoidungchinhLayout.setVerticalGroup(
            jPnoidungchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnoidungchinhLayout.createSequentialGroup()
                .addComponent(jPnoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPchinhsua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPgoc.add(jPnoidungchinh, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPgoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPgoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSID_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSID_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSID_menuActionPerformed

    @SuppressWarnings("empty-statement")
    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        String url = "jdbc:jtds:sqlserver://localhost:1433/bookssupplier";
        String user = "sa";
        String password = "123";
        String sql = "INSERT INTO Employee" + " VALUES (?, ?, ?, ?, ?, ?, ? )";
        PreparedStatement preStmt = null;
        String SUPID = jTSID.getText();
        String SUPNAME = jTSName.getText();
        String SUPTYPE = "";
        if(jCBooks.isSelected())
        {
            SUPTYPE = SUPTYPE + " Books";
        }if (jCBooks.isSelected())
        {
            SUPTYPE = SUPTYPE + " News";
        }if (jCBooks.isSelected())
        {
            SUPTYPE = SUPTYPE + " Journals and Magazines";
        }
        String ADDR = jTAddress.getText();
        String CONTACT = jTContact.getText();
        String EMAIL = jTEmail.getText();
        String REMARKS = jLRemarks.getText();
        int row =0;
        try {
            conn = (Connection) DriverManager.getConnection(url, user, password);
            preStmt = conn.prepareStatement(sql);
            
            preStmt.setString(1,SUPID);
            preStmt.setString(2, SUPNAME);
            preStmt.setString(3, SUPTYPE);
            preStmt.setString(4, ADDR);
            preStmt.setString(5, CONTACT);
            preStmt.setString(6, EMAIL);
            preStmt.setString(7, REMARKS);
            row = preStmt.executeUpdate();
            System.out.println("row inserted" + row);
            conn.close();;
           
        } catch (SQLException ex) {
            Logger.getLogger(baitaptuan4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baitaptuan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baitaptuan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baitaptuan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baitaptuan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baitaptuan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBooks_menu;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBJournals;
    private javax.swing.JButton jBNew;
    private javax.swing.JButton jBNews;
    private javax.swing.JButton jBRong;
    private javax.swing.JButton jBSID_menu;
    private javax.swing.JButton jBSName_menu;
    private javax.swing.JButton jBSave;
    private javax.swing.JButton jBUpdate;
    private javax.swing.JCheckBox jCBooks;
    private javax.swing.JCheckBox jCJournals;
    private javax.swing.JCheckBox jCNews;
    private javax.swing.JLabel jLAddress;
    private javax.swing.JLabel jLContact;
    private javax.swing.JLabel jLMail;
    private javax.swing.JLabel jLRemarks;
    private javax.swing.JLabel jLSID;
    private javax.swing.JLabel jLSName;
    private javax.swing.JLabel jLType;
    private javax.swing.JPanel jPchinhsua;
    private javax.swing.JPanel jPgoc;
    private javax.swing.JPanel jPmenu;
    private javax.swing.JPanel jPnoidung;
    private javax.swing.JPanel jPnoidungchinh;
    private javax.swing.JPanel jPtieude;
    private javax.swing.JScrollPane jSCP;
    private javax.swing.JTextField jTAddress;
    private javax.swing.JTextField jTContact;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextArea jTRemarks;
    private javax.swing.JTextField jTSID;
    private javax.swing.JTextField jTSName;
    private javax.swing.JTextField jTtieude;
    // End of variables declaration//GEN-END:variables
}
