use bookssupplier
create table bookssup (
	SUPID NVARCHAR(10),
	SUPNAME NVARCHAR(50),
	SUPTYPE NVARCHAR(50),
	ADDR NVARCHAR(60),
	CONTACT NVARCHAR(20),
	EMAIL NVARCHAR(30),
	REMARKS NVARCHAR(90),
	PRIMARY KEY (SUPID),

)