/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Baihoctuan5;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author admin
 */
public class Baitaptuan5 extends javax.swing.JFrame {

    

   

    /** Creates new form new1 */
    public Baitaptuan5() {
        initComponents();
        showNhanVien();
    }
     private List<NhanVien> getAllNhanVien(){
        List<NhanVien> listAllE = new ArrayList<>();
        
        Connection conn = null;
        String url = "jdbc:jtds:sqlserver://localhost:1433/bookssupplier";
        String user ="sa";
        String password = "123";
        String sql = "SELECT * FORM Employees";
        ResultSet rsNhanVien;
        Statement stmt;
        try {
            conn = DriverManager.getConnection(url, user, password);
            stmt = conn.createStatement();
            rsNhanVien = stmt.executeQuery(sql);
            
            NhanVien nhanvien = null;
            while(rsNhanVien.next()){
                nhanvien = new NhanVien();
                nhanvien.setName(rsNhanVien.getString("Name"));
                nhanvien.setAddress(rsNhanVien.getString("Address"));
                nhanvien.setGender(rsNhanVien.getString("Gender"));
                nhanvien.setKnowledge(rsNhanVien.getString("Knowledge"));
                nhanvien.setSubject(rsNhanVien.getString("Subject"));
                
                listAllE.add(nhanvien);
                
                
            }
            conn.close();
            rsNhanVien.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Baitaptuan5.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return listAllE;
        
    }
    private void showNhanVien(){
        List<NhanVien> listAllE = getAllNhanVien();
        DefaultTableModel model = 
            (DefaultTableModel)jT_1.getModel();
        Object []row = new Object[5];
        for (int i = 0; i < listAllE.size(); i++)
        {
           row [0] = listAllE.get(1).getName();
           row [2] = listAllE.get(2).getAddress();
           row [3] = listAllE.get(3).getGender();
           row [4] = listAllE.get(4).getKnowledge();
           row [5] = listAllE.get(5).getSubject();
           model.addRow(row);
        }
        
        
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPGoc = new javax.swing.JPanel();
        text_name = new javax.swing.JTextField();
        text_add = new javax.swing.JTextField();
        address_jb = new javax.swing.JLabel();
        name_jb = new javax.swing.JLabel();
        grender_jb = new javax.swing.JLabel();
        subjet_jb = new javax.swing.JLabel();
        knowledge_jb = new javax.swing.JLabel();
        male_jr = new javax.swing.JRadioButton();
        female_jr = new javax.swing.JRadioButton();
        jCJava = new javax.swing.JCheckBox();
        jCTyphon = new javax.swing.JCheckBox();
        save_b = new javax.swing.JButton();
        reset_b = new javax.swing.JButton();
        Subject_box = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        address_jb.setText("Address");

        name_jb.setText("Name");

        grender_jb.setText("Grender");

        subjet_jb.setText("Subject");

        knowledge_jb.setText("Knowledge");

        buttonGroup1.add(male_jr);
        male_jr.setText("Male");

        buttonGroup1.add(female_jr);
        female_jr.setText("Female");

        jCJava.setText("Java");

        jCTyphon.setText("Typhon");
        jCTyphon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTyphonActionPerformed(evt);
            }
        });

        save_b.setText("Save...");
        save_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_bActionPerformed(evt);
            }
        });

        reset_b.setText("Reset");

        Subject_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Bussiness", "Eductation", "Developer" }));
        Subject_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject_boxActionPerformed(evt);
            }
        });

        jT_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Gender", "Knowledge", "Subject"
            }
        ));
        jScrollPane1.setViewportView(jT_1);

        javax.swing.GroupLayout jPGocLayout = new javax.swing.GroupLayout(jPGoc);
        jPGoc.setLayout(jPGocLayout);
        jPGocLayout.setHorizontalGroup(
            jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGocLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPGocLayout.createSequentialGroup()
                        .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subjet_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grender_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Subject_box, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPGocLayout.createSequentialGroup()
                        .addComponent(knowledge_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save_b, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_add, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPGocLayout.createSequentialGroup()
                                    .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(male_jr, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCJava, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCTyphon, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(female_jr, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reset_b, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(text_name)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPGocLayout.setVerticalGroup(
            jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGocLayout.createSequentialGroup()
                .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPGocLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPGocLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grender_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(male_jr)
                            .addComponent(female_jr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(knowledge_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCJava)
                            .addComponent(jCTyphon))
                        .addGap(20, 20, 20)
                        .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjet_jb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Subject_box, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save_b)
                            .addComponent(reset_b))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void save_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_bActionPerformed
        // TODO add your handling code here:
        //xu ly code luu du lieu 
        //1. ket noi csdl ten la DBQLNV-2019
        Connection conn = null;
        String url = "jdbc:jtds:sqlserver://localhost:1433/bookssupplier";
        String user ="sa";
        String password = "123";
        String sql = "INSERT INTO Employees"
            + "VALUE (?, ?, ?, ?, ? )";
        PreparedStatement preStmt = null;
        String strName = text_name.getText();
        String strDiaChi = text_add.getText();
        int row = 0;
        String strGioitinh = "";
        if(male_jr.isSelected())
        {
            strGioitinh = "Male";
        }else{
            strGioitinh = "Female";
        }
        String strKnowledge = "";
        if(jCJava.isSelected())
        {
            strKnowledge = strKnowledge + "Java";
        }if (jCJava.isSelected())
        {
            strKnowledge = strKnowledge + "java";
        }
        
        
        String strsubject = "";
        strsubject = Subject_box.getSelectedItem().toString();
        
        try {
            conn = DriverManager.getConnection(url, user, password);
            preStmt = conn.prepareStatement(sql);
            
            preStmt.setString(1, strName);
            preStmt.setString(2, strDiaChi);
            preStmt.setString(3, strGioitinh);
            preStmt.setString(4, strKnowledge);
            preStmt.setString(5, strsubject);
            
            row = preStmt.executeUpdate();
            System.out.println("row inserted" + row);
            conn.close();;
        } catch (SQLException ex) {
            Logger.getLogger(Baitaptuan5.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_save_bActionPerformed

    private void jCTyphonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTyphonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTyphonActionPerformed

    private void Subject_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Subject_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Baitaptuan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Baitaptuan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Baitaptuan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Baitaptuan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Baitaptuan5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Subject_box;
    private javax.swing.JLabel address_jb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female_jr;
    private javax.swing.JLabel grender_jb;
    private javax.swing.JCheckBox jCJava;
    private javax.swing.JCheckBox jCTyphon;
    private javax.swing.JPanel jPGoc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_1;
    private javax.swing.JLabel knowledge_jb;
    private javax.swing.JRadioButton male_jr;
    private javax.swing.JLabel name_jb;
    private javax.swing.JButton reset_b;
    private javax.swing.JButton save_b;
    private javax.swing.JLabel subjet_jb;
    private javax.swing.JTextField text_add;
    private javax.swing.JTextField text_name;
    // End of variables declaration//GEN-END:variables

    

}
