/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lad1_bai2;

/**
 *
 * @author admin
 */
public class Lad1_bai2 extends javax.swing.JFrame {

    /**
     * Creates new form Lad1_bai2
     */
    public Lad1_bai2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPGoc = new javax.swing.JPanel();
        jPW = new javax.swing.JPanel();
        jPS = new javax.swing.JPanel();
        jPE = new javax.swing.JPanel();
        jPN = new javax.swing.JPanel();
        jPC = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPGoc.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPWLayout = new javax.swing.GroupLayout(jPW);
        jPW.setLayout(jPWLayout);
        jPWLayout.setHorizontalGroup(
            jPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPWLayout.setVerticalGroup(
            jPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPGoc.add(jPW, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPSLayout = new javax.swing.GroupLayout(jPS);
        jPS.setLayout(jPSLayout);
        jPSLayout.setHorizontalGroup(
            jPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPSLayout.setVerticalGroup(
            jPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPGoc.add(jPS, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPELayout = new javax.swing.GroupLayout(jPE);
        jPE.setLayout(jPELayout);
        jPELayout.setHorizontalGroup(
            jPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPELayout.setVerticalGroup(
            jPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPGoc.add(jPE, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPNLayout = new javax.swing.GroupLayout(jPN);
        jPN.setLayout(jPNLayout);
        jPNLayout.setHorizontalGroup(
            jPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPNLayout.setVerticalGroup(
            jPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPGoc.add(jPN, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPCLayout = new javax.swing.GroupLayout(jPC);
        jPC.setLayout(jPCLayout);
        jPCLayout.setHorizontalGroup(
            jPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPCLayout.setVerticalGroup(
            jPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPGoc.add(jPC, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lad1_bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lad1_bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lad1_bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lad1_bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lad1_bai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPC;
    private javax.swing.JPanel jPE;
    private javax.swing.JPanel jPGoc;
    private javax.swing.JPanel jPN;
    private javax.swing.JPanel jPS;
    private javax.swing.JPanel jPW;
    // End of variables declaration//GEN-END:variables
}
